title: Veronica Saz Ulibarrena
description: Aerospace Engineer, Computational Astrophysics, Machine Learning and Optimization expert
show_downloads: false
google_analytics:
theme: jekyll-theme-cayman
